env:
  browser: true
  es6: true
extends: ["plugin:prettier/recommended", "prettier/react"]
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: babel-eslint
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
      bracketSpacing: false