language: node_js
node_js: '12'
script:
  - npm run build
  - npm run test
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      node: 12
  - provider: pages
    skip_cleanup: true
    local_dir: build
    github_token: $GITHUB_TOKEN
    keep_history: true
    email: watdevex@us.ibm.com
    name: Watson Github Bot
    on:
      branch: master
